services:
  db:
    image: postgres:18.4-alpine
    ports:
      - "5433:5432"
    restart: unless-stopped
    shm_size: 128mb
    environment:
      POSTGRES_USER: testuser
      POSTGRES_PASSWORD: testpass
      POSTGRES_DB: testdb
    volumes:
      - ./pgdata:/var/lib/postgresql
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "testuser", "-d", "postgres"]
      start_period: 3s

  mail:
    image: maildev/maildev
    restart: unless-stopped
    ports:
      - "1080:1080"
      - "1025:1025" # expose SMTP to host
    healthcheck:
      test:
        [
          "CMD",
          "wget",
          "--quiet",
          "--tries=1",
          "--spider",
          "http://localhost:1080",
        ]

  migration:
    build:
      context: .
      dockerfile: apps/api/Dockerfile
      target: builder
    command: bun run --filter @kaja/api db:push -- --force
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - path: apps/api/.env.example
        required: true
      - path: apps/api/.env
        required: false
    environment:
      DATABASE_URL: postgresql://testuser:testpass@db:5432/testdb

  api:
    build:
      context: .
      dockerfile: apps/api/Dockerfile
    ports:
      - "3001:3001"
    depends_on:
      db:
        condition: service_healthy
      migration:
        condition: service_completed_successfully
      mail:
        condition: service_healthy
    env_file:
      - path: apps/api/.env.example
        required: true
      - path: apps/api/.env
        required: false
    environment:
      DATABASE_URL: postgresql://testuser:testpass@db:5432/testdb
      SMTP_HOST: mail

  web:
    build:
      context: .
      dockerfile: apps/web/Dockerfile
      args:
        VITE_API_URL: ${VITE_API_URL:-http://localhost:3001}
        VITE_APP_URL: ${VITE_APP_URL:-http://localhost:3000}
    ports:
      - "3000:3000"
    depends_on:
      - api
    env_file:
      - path: apps/web/.env.example
        required: true
      - path: apps/web/.env
        required: false
    environment:
      API_URL: http://api:3001
