// Generated by `bun run scripts/env-types.ts` from packages/schema/env — do not edit by hand.

declare module "bun" {
  interface Env {
    /** Overrides [api].baseUrl from services.toml, for pointing the CLI at a local dev API without editing the file */
    KAJA_API_URL?: string
    /** Minimum level written to KAJA_LOG_FILE (trace, debug, info, warn, error, fatal); unset means no log */
    KAJA_LOG_LEVEL?: string
    /** Append JSON-lines logs here (needs KAJA_LOG_LEVEL); the TUI never logs to the terminal */
    KAJA_LOG_FILE?: string
  }
}

export {}
