// Generated by `bun run scripts/env-types.ts` from packages/schema/env — do not edit by hand.

declare module "bun" {
  interface Env {
    /** The Kaja API the CLI talks to, for pointing it at a local dev API; defaults to https://api.kaja.io */
    KAJA_API_URL?: string
    /** Minimum level written to KAJA_LOG_FILE (trace, debug, info, warn, error, fatal); unset means no log */
    KAJA_LOG_LEVEL?: string
    /** Append JSON-lines logs here (needs KAJA_LOG_LEVEL); the TUI never logs to the terminal */
    KAJA_LOG_FILE?: string
  }
}

export {}
