// Generated by `bun run scripts/env-types.ts` from packages/schema/env — do not edit by hand.

declare module "bun" {
  interface Env {
    /** Selects @kaja/logger's node.ts destination: pretty-print in development, Axiom in production */
    NODE_ENV?: string
    /** App name attached to every log line */
    KAJA_APP_NAME?: string
    /** Master on/off switch for logging - unset means no log output at all */
    KAJA_LOG_LEVEL?: string
    /** Append JSON logs here instead of pretty-printing/Axiom, in any NODE_ENV */
    KAJA_LOG_FILE?: string
    /** Axiom dataset to ship logs to (node, NODE_ENV=production, no KAJA_LOG_FILE) */
    AXIOM_DATASET?: string
    /** Axiom ingest token (node, NODE_ENV=production, no KAJA_LOG_FILE) */
    AXIOM_TOKEN?: string
    /** Server-to-server API base URL — set by compose/disco to the container-network address (e.g. http://api:3001); takes precedence over VITE_API_URL when both are set */
    API_URL?: string
    /** Browser-facing API base URL, baked into the client bundle */
    VITE_API_URL?: string
    /** Public web app URL */
    VITE_APP_URL?: string
    /** Widget key pinned to the barkochba persona, used by the landing page's playable hero demo. Intentionally public — the Origin allowlist is the real gate, not key secrecy. */
    VITE_WIDGET_BARKOCHBA_KEY?: string
    /** Second widget key, on a separate dedicated demo account, used by the landing page's embeddable chat widget script. */
    VITE_WIDGET_CHAT_KEY?: string
    /** Sentry auth token used by the build-time Vite plugin to upload source maps */
    SENTRY_AUTH_TOKEN?: string
  }
}

export {}
