// Generated by `bun run scripts/env-types.ts` from packages/schema/env — do not edit by hand.

declare module "bun" {
  interface Env {
    /** Server-to-server API base URL — set by compose/disco to the container-network address (e.g. http://api:3001); takes precedence over VITE_API_URL when both are set */
    API_URL?: string
    /** Browser-facing API base URL, baked into the client bundle */
    VITE_API_URL?: string
    /** Public web app URL */
    VITE_APP_URL?: string
    /** Widget key pinned to the barkochba persona, used by the landing page's playable hero demo. Intentionally public — the Origin allowlist is the real gate, not key secrecy. */
    VITE_WIDGET_BARKOCHBA_KEY?: string
    /** Second widget key, on a separate dedicated demo account, used by the landing page's embeddable chat widget script. */
    VITE_WIDGET_CHAT_KEY?: string
    /** Umami analytics website id */
    VITE_UMAMI_WEBSITE_ID?: string
  }
}

export {}
