/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PublicRouteImport } from './routes/_public'
import { Route as AdminRouteImport } from './routes/_admin'
import { Route as PublicIndexRouteImport } from './routes/_public/index'
import { Route as AdminProfileRouteImport } from './routes/_admin/profile'
import { Route as AdminDashboardRouteImport } from './routes/_admin/dashboard'
import { Route as AdminUsersIndexRouteImport } from './routes/_admin/users/index'
import { Route as AdminNodesIndexRouteImport } from './routes/_admin/nodes/index'
import { Route as PublicauthSignupRouteImport } from './routes/_public/(auth)/signup'
import { Route as PublicauthSigninRouteImport } from './routes/_public/(auth)/signin'
import { Route as PublicauthResetPasswordRouteImport } from './routes/_public/(auth)/reset-password'
import { Route as PublicauthDeviceRouteImport } from './routes/_public/(auth)/device'
import { Route as AdminUsersUserIdRouteImport } from './routes/_admin/users/$userId'
import { Route as PublicauthDeviceIndexRouteImport } from './routes/_public/(auth)/device/index'
import { Route as PublicauthDeviceApproveRouteImport } from './routes/_public/(auth)/device/approve'

const PublicRoute = PublicRouteImport.update({
  id: '/_public',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/_admin',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicIndexRoute = PublicIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PublicRoute,
} as any)
const AdminProfileRoute = AdminProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDashboardRoute = AdminDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AdminRoute,
} as any)
const AdminUsersIndexRoute = AdminUsersIndexRouteImport.update({
  id: '/users/',
  path: '/users/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminNodesIndexRoute = AdminNodesIndexRouteImport.update({
  id: '/nodes/',
  path: '/nodes/',
  getParentRoute: () => AdminRoute,
} as any)
const PublicauthSignupRoute = PublicauthSignupRouteImport.update({
  id: '/(auth)/signup',
  path: '/signup',
  getParentRoute: () => PublicRoute,
} as any)
const PublicauthSigninRoute = PublicauthSigninRouteImport.update({
  id: '/(auth)/signin',
  path: '/signin',
  getParentRoute: () => PublicRoute,
} as any)
const PublicauthResetPasswordRoute = PublicauthResetPasswordRouteImport.update({
  id: '/(auth)/reset-password',
  path: '/reset-password',
  getParentRoute: () => PublicRoute,
} as any)
const PublicauthDeviceRoute = PublicauthDeviceRouteImport.update({
  id: '/(auth)/device',
  path: '/device',
  getParentRoute: () => PublicRoute,
} as any)
const AdminUsersUserIdRoute = AdminUsersUserIdRouteImport.update({
  id: '/users/$userId',
  path: '/users/$userId',
  getParentRoute: () => AdminRoute,
} as any)
const PublicauthDeviceIndexRoute = PublicauthDeviceIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PublicauthDeviceRoute,
} as any)
const PublicauthDeviceApproveRoute = PublicauthDeviceApproveRouteImport.update({
  id: '/approve',
  path: '/approve',
  getParentRoute: () => PublicauthDeviceRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof PublicIndexRoute
  '/dashboard': typeof AdminDashboardRoute
  '/profile': typeof AdminProfileRoute
  '/users/$userId': typeof AdminUsersUserIdRoute
  '/device': typeof PublicauthDeviceRouteWithChildren
  '/reset-password': typeof PublicauthResetPasswordRoute
  '/signin': typeof PublicauthSigninRoute
  '/signup': typeof PublicauthSignupRoute
  '/nodes/': typeof AdminNodesIndexRoute
  '/users/': typeof AdminUsersIndexRoute
  '/device/approve': typeof PublicauthDeviceApproveRoute
  '/device/': typeof PublicauthDeviceIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof PublicIndexRoute
  '/dashboard': typeof AdminDashboardRoute
  '/profile': typeof AdminProfileRoute
  '/users/$userId': typeof AdminUsersUserIdRoute
  '/reset-password': typeof PublicauthResetPasswordRoute
  '/signin': typeof PublicauthSigninRoute
  '/signup': typeof PublicauthSignupRoute
  '/nodes': typeof AdminNodesIndexRoute
  '/users': typeof AdminUsersIndexRoute
  '/device/approve': typeof PublicauthDeviceApproveRoute
  '/device': typeof PublicauthDeviceIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_admin': typeof AdminRouteWithChildren
  '/_public': typeof PublicRouteWithChildren
  '/_admin/dashboard': typeof AdminDashboardRoute
  '/_admin/profile': typeof AdminProfileRoute
  '/_public/': typeof PublicIndexRoute
  '/_admin/users/$userId': typeof AdminUsersUserIdRoute
  '/_public/(auth)/device': typeof PublicauthDeviceRouteWithChildren
  '/_public/(auth)/reset-password': typeof PublicauthResetPasswordRoute
  '/_public/(auth)/signin': typeof PublicauthSigninRoute
  '/_public/(auth)/signup': typeof PublicauthSignupRoute
  '/_admin/nodes/': typeof AdminNodesIndexRoute
  '/_admin/users/': typeof AdminUsersIndexRoute
  '/_public/(auth)/device/approve': typeof PublicauthDeviceApproveRoute
  '/_public/(auth)/device/': typeof PublicauthDeviceIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/profile'
    | '/users/$userId'
    | '/device'
    | '/reset-password'
    | '/signin'
    | '/signup'
    | '/nodes/'
    | '/users/'
    | '/device/approve'
    | '/device/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/profile'
    | '/users/$userId'
    | '/reset-password'
    | '/signin'
    | '/signup'
    | '/nodes'
    | '/users'
    | '/device/approve'
    | '/device'
  id:
    | '__root__'
    | '/_admin'
    | '/_public'
    | '/_admin/dashboard'
    | '/_admin/profile'
    | '/_public/'
    | '/_admin/users/$userId'
    | '/_public/(auth)/device'
    | '/_public/(auth)/reset-password'
    | '/_public/(auth)/signin'
    | '/_public/(auth)/signup'
    | '/_admin/nodes/'
    | '/_admin/users/'
    | '/_public/(auth)/device/approve'
    | '/_public/(auth)/device/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AdminRoute: typeof AdminRouteWithChildren
  PublicRoute: typeof PublicRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_public': {
      id: '/_public'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof PublicRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_admin': {
      id: '/_admin'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public/': {
      id: '/_public/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof PublicIndexRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_admin/profile': {
      id: '/_admin/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AdminProfileRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/dashboard': {
      id: '/_admin/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AdminDashboardRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/users/': {
      id: '/_admin/users/'
      path: '/users'
      fullPath: '/users/'
      preLoaderRoute: typeof AdminUsersIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/nodes/': {
      id: '/_admin/nodes/'
      path: '/nodes'
      fullPath: '/nodes/'
      preLoaderRoute: typeof AdminNodesIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_public/(auth)/signup': {
      id: '/_public/(auth)/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof PublicauthSignupRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/(auth)/signin': {
      id: '/_public/(auth)/signin'
      path: '/signin'
      fullPath: '/signin'
      preLoaderRoute: typeof PublicauthSigninRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/(auth)/reset-password': {
      id: '/_public/(auth)/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof PublicauthResetPasswordRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/(auth)/device': {
      id: '/_public/(auth)/device'
      path: '/device'
      fullPath: '/device'
      preLoaderRoute: typeof PublicauthDeviceRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_admin/users/$userId': {
      id: '/_admin/users/$userId'
      path: '/users/$userId'
      fullPath: '/users/$userId'
      preLoaderRoute: typeof AdminUsersUserIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_public/(auth)/device/': {
      id: '/_public/(auth)/device/'
      path: '/'
      fullPath: '/device/'
      preLoaderRoute: typeof PublicauthDeviceIndexRouteImport
      parentRoute: typeof PublicauthDeviceRoute
    }
    '/_public/(auth)/device/approve': {
      id: '/_public/(auth)/device/approve'
      path: '/approve'
      fullPath: '/device/approve'
      preLoaderRoute: typeof PublicauthDeviceApproveRouteImport
      parentRoute: typeof PublicauthDeviceRoute
    }
  }
}

interface AdminRouteChildren {
  AdminDashboardRoute: typeof AdminDashboardRoute
  AdminProfileRoute: typeof AdminProfileRoute
  AdminUsersUserIdRoute: typeof AdminUsersUserIdRoute
  AdminNodesIndexRoute: typeof AdminNodesIndexRoute
  AdminUsersIndexRoute: typeof AdminUsersIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminDashboardRoute: AdminDashboardRoute,
  AdminProfileRoute: AdminProfileRoute,
  AdminUsersUserIdRoute: AdminUsersUserIdRoute,
  AdminNodesIndexRoute: AdminNodesIndexRoute,
  AdminUsersIndexRoute: AdminUsersIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface PublicauthDeviceRouteChildren {
  PublicauthDeviceApproveRoute: typeof PublicauthDeviceApproveRoute
  PublicauthDeviceIndexRoute: typeof PublicauthDeviceIndexRoute
}

const PublicauthDeviceRouteChildren: PublicauthDeviceRouteChildren = {
  PublicauthDeviceApproveRoute: PublicauthDeviceApproveRoute,
  PublicauthDeviceIndexRoute: PublicauthDeviceIndexRoute,
}

const PublicauthDeviceRouteWithChildren =
  PublicauthDeviceRoute._addFileChildren(PublicauthDeviceRouteChildren)

interface PublicRouteChildren {
  PublicIndexRoute: typeof PublicIndexRoute
  PublicauthDeviceRoute: typeof PublicauthDeviceRouteWithChildren
  PublicauthResetPasswordRoute: typeof PublicauthResetPasswordRoute
  PublicauthSigninRoute: typeof PublicauthSigninRoute
  PublicauthSignupRoute: typeof PublicauthSignupRoute
}

const PublicRouteChildren: PublicRouteChildren = {
  PublicIndexRoute: PublicIndexRoute,
  PublicauthDeviceRoute: PublicauthDeviceRouteWithChildren,
  PublicauthResetPasswordRoute: PublicauthResetPasswordRoute,
  PublicauthSigninRoute: PublicauthSigninRoute,
  PublicauthSignupRoute: PublicauthSignupRoute,
}

const PublicRouteWithChildren =
  PublicRoute._addFileChildren(PublicRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AdminRoute: AdminRouteWithChildren,
  PublicRoute: PublicRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
