/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AdminRouteImport } from './routes/_admin'
import { Route as PublicRouteImport } from './routes/_public'
import { Route as UDotjsRouteImport } from './routes/u[.]js'
import { Route as AdminDashboardRouteImport } from './routes/_admin/dashboard'
import { Route as AdminProfileRouteImport } from './routes/_admin/profile'
import { Route as PublicLandingRouteImport } from './routes/_public/_landing'
import { Route as ApiSendRouteImport } from './routes/api/send'
import { Route as AdminMcpServersIndexRouteImport } from './routes/_admin/mcp-servers/index'
import { Route as AdminModelsIndexRouteImport } from './routes/_admin/models/index'
import { Route as AdminNodesIndexRouteImport } from './routes/_admin/nodes/index'
import { Route as AdminUsersIndexRouteImport } from './routes/_admin/users/index'
import { Route as AdminUsersUserIdRouteImport } from './routes/_admin/users/$userId'
import { Route as PublicauthDeviceRouteImport } from './routes/_public/(auth)/device'
import { Route as PublicauthResetPasswordRouteImport } from './routes/_public/(auth)/reset-password'
import { Route as PublicLandingIndexRouteImport } from './routes/_public/_landing/index'
import { Route as PublicLandingArchitectureRouteImport } from './routes/_public/_landing/architecture'
import { Route as PublicauthDeviceIndexRouteImport } from './routes/_public/(auth)/device/index'
import { Route as PublicauthDeviceApproveRouteImport } from './routes/_public/(auth)/device/approve'
import { Route as PublicLandingauthSigninRouteImport } from './routes/_public/_landing/(auth)/signin'
import { Route as PublicLandingauthSignupRouteImport } from './routes/_public/_landing/(auth)/signup'

const AdminRoute = AdminRouteImport.update({
  id: '/_admin',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicRoute = PublicRouteImport.update({
  id: '/_public',
  getParentRoute: () => rootRouteImport,
} as any)
const UDotjsRoute = UDotjsRouteImport.update({
  id: '/u.js',
  path: '/u.js',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminDashboardRoute = AdminDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProfileRoute = AdminProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AdminRoute,
} as any)
const PublicLandingRoute = PublicLandingRouteImport.update({
  id: '/_landing',
  getParentRoute: () => PublicRoute,
} as any)
const ApiSendRoute = ApiSendRouteImport.update({
  id: '/api/send',
  path: '/api/send',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminMcpServersIndexRoute = AdminMcpServersIndexRouteImport.update({
  id: '/mcp-servers/',
  path: '/mcp-servers/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminModelsIndexRoute = AdminModelsIndexRouteImport.update({
  id: '/models/',
  path: '/models/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminNodesIndexRoute = AdminNodesIndexRouteImport.update({
  id: '/nodes/',
  path: '/nodes/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminUsersIndexRoute = AdminUsersIndexRouteImport.update({
  id: '/users/',
  path: '/users/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminUsersUserIdRoute = AdminUsersUserIdRouteImport.update({
  id: '/users/$userId',
  path: '/users/$userId',
  getParentRoute: () => AdminRoute,
} as any)
const PublicauthDeviceRoute = PublicauthDeviceRouteImport.update({
  id: '/(auth)/device',
  path: '/device',
  getParentRoute: () => PublicRoute,
} as any)
const PublicauthResetPasswordRoute = PublicauthResetPasswordRouteImport.update({
  id: '/(auth)/reset-password',
  path: '/reset-password',
  getParentRoute: () => PublicRoute,
} as any)
const PublicLandingIndexRoute = PublicLandingIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PublicLandingRoute,
} as any)
const PublicLandingArchitectureRoute =
  PublicLandingArchitectureRouteImport.update({
    id: '/architecture',
    path: '/architecture',
    getParentRoute: () => PublicLandingRoute,
  } as any)
const PublicauthDeviceIndexRoute = PublicauthDeviceIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PublicauthDeviceRoute,
} as any)
const PublicauthDeviceApproveRoute = PublicauthDeviceApproveRouteImport.update({
  id: '/approve',
  path: '/approve',
  getParentRoute: () => PublicauthDeviceRoute,
} as any)
const PublicLandingauthSigninRoute = PublicLandingauthSigninRouteImport.update({
  id: '/(auth)/signin',
  path: '/signin',
  getParentRoute: () => PublicLandingRoute,
} as any)
const PublicLandingauthSignupRoute = PublicLandingauthSignupRouteImport.update({
  id: '/(auth)/signup',
  path: '/signup',
  getParentRoute: () => PublicLandingRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof PublicLandingIndexRoute
  '/u.js': typeof UDotjsRoute
  '/dashboard': typeof AdminDashboardRoute
  '/profile': typeof AdminProfileRoute
  '/api/send': typeof ApiSendRoute
  '/users/$userId': typeof AdminUsersUserIdRoute
  '/device': typeof PublicauthDeviceRouteWithChildren
  '/reset-password': typeof PublicauthResetPasswordRoute
  '/architecture': typeof PublicLandingArchitectureRoute
  '/mcp-servers/': typeof AdminMcpServersIndexRoute
  '/models/': typeof AdminModelsIndexRoute
  '/nodes/': typeof AdminNodesIndexRoute
  '/users/': typeof AdminUsersIndexRoute
  '/device/approve': typeof PublicauthDeviceApproveRoute
  '/signin': typeof PublicLandingauthSigninRoute
  '/signup': typeof PublicLandingauthSignupRoute
  '/device/': typeof PublicauthDeviceIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof PublicLandingIndexRoute
  '/u.js': typeof UDotjsRoute
  '/dashboard': typeof AdminDashboardRoute
  '/profile': typeof AdminProfileRoute
  '/api/send': typeof ApiSendRoute
  '/users/$userId': typeof AdminUsersUserIdRoute
  '/reset-password': typeof PublicauthResetPasswordRoute
  '/architecture': typeof PublicLandingArchitectureRoute
  '/mcp-servers': typeof AdminMcpServersIndexRoute
  '/models': typeof AdminModelsIndexRoute
  '/nodes': typeof AdminNodesIndexRoute
  '/users': typeof AdminUsersIndexRoute
  '/device/approve': typeof PublicauthDeviceApproveRoute
  '/signin': typeof PublicLandingauthSigninRoute
  '/signup': typeof PublicLandingauthSignupRoute
  '/device': typeof PublicauthDeviceIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_admin': typeof AdminRouteWithChildren
  '/_public': typeof PublicRouteWithChildren
  '/u.js': typeof UDotjsRoute
  '/_admin/dashboard': typeof AdminDashboardRoute
  '/_admin/profile': typeof AdminProfileRoute
  '/_public/_landing': typeof PublicLandingRouteWithChildren
  '/api/send': typeof ApiSendRoute
  '/_admin/users/$userId': typeof AdminUsersUserIdRoute
  '/_public/(auth)/device': typeof PublicauthDeviceRouteWithChildren
  '/_public/(auth)/reset-password': typeof PublicauthResetPasswordRoute
  '/_public/_landing/architecture': typeof PublicLandingArchitectureRoute
  '/_admin/mcp-servers/': typeof AdminMcpServersIndexRoute
  '/_admin/models/': typeof AdminModelsIndexRoute
  '/_admin/nodes/': typeof AdminNodesIndexRoute
  '/_admin/users/': typeof AdminUsersIndexRoute
  '/_public/_landing/': typeof PublicLandingIndexRoute
  '/_public/(auth)/device/approve': typeof PublicauthDeviceApproveRoute
  '/_public/_landing/(auth)/signin': typeof PublicLandingauthSigninRoute
  '/_public/_landing/(auth)/signup': typeof PublicLandingauthSignupRoute
  '/_public/(auth)/device/': typeof PublicauthDeviceIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/u.js'
    | '/dashboard'
    | '/profile'
    | '/api/send'
    | '/users/$userId'
    | '/device'
    | '/reset-password'
    | '/architecture'
    | '/mcp-servers/'
    | '/models/'
    | '/nodes/'
    | '/users/'
    | '/device/approve'
    | '/signin'
    | '/signup'
    | '/device/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/u.js'
    | '/dashboard'
    | '/profile'
    | '/api/send'
    | '/users/$userId'
    | '/reset-password'
    | '/architecture'
    | '/mcp-servers'
    | '/models'
    | '/nodes'
    | '/users'
    | '/device/approve'
    | '/signin'
    | '/signup'
    | '/device'
  id:
    | '__root__'
    | '/_admin'
    | '/_public'
    | '/u.js'
    | '/_admin/dashboard'
    | '/_admin/profile'
    | '/_public/_landing'
    | '/api/send'
    | '/_admin/users/$userId'
    | '/_public/(auth)/device'
    | '/_public/(auth)/reset-password'
    | '/_public/_landing/architecture'
    | '/_admin/mcp-servers/'
    | '/_admin/models/'
    | '/_admin/nodes/'
    | '/_admin/users/'
    | '/_public/_landing/'
    | '/_public/(auth)/device/approve'
    | '/_public/_landing/(auth)/signin'
    | '/_public/_landing/(auth)/signup'
    | '/_public/(auth)/device/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AdminRoute: typeof AdminRouteWithChildren
  PublicRoute: typeof PublicRouteWithChildren
  UDotjsRoute: typeof UDotjsRoute
  ApiSendRoute: typeof ApiSendRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_admin': {
      id: '/_admin'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public': {
      id: '/_public'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof PublicRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/u.js': {
      id: '/u.js'
      path: '/u.js'
      fullPath: '/u.js'
      preLoaderRoute: typeof UDotjsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_admin/dashboard': {
      id: '/_admin/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AdminDashboardRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/profile': {
      id: '/_admin/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AdminProfileRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_public/_landing': {
      id: '/_public/_landing'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof PublicLandingRouteImport
      parentRoute: typeof PublicRoute
    }
    '/api/send': {
      id: '/api/send'
      path: '/api/send'
      fullPath: '/api/send'
      preLoaderRoute: typeof ApiSendRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_admin/mcp-servers/': {
      id: '/_admin/mcp-servers/'
      path: '/mcp-servers'
      fullPath: '/mcp-servers/'
      preLoaderRoute: typeof AdminMcpServersIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/models/': {
      id: '/_admin/models/'
      path: '/models'
      fullPath: '/models/'
      preLoaderRoute: typeof AdminModelsIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/nodes/': {
      id: '/_admin/nodes/'
      path: '/nodes'
      fullPath: '/nodes/'
      preLoaderRoute: typeof AdminNodesIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/users/': {
      id: '/_admin/users/'
      path: '/users'
      fullPath: '/users/'
      preLoaderRoute: typeof AdminUsersIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/users/$userId': {
      id: '/_admin/users/$userId'
      path: '/users/$userId'
      fullPath: '/users/$userId'
      preLoaderRoute: typeof AdminUsersUserIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_public/(auth)/device': {
      id: '/_public/(auth)/device'
      path: '/device'
      fullPath: '/device'
      preLoaderRoute: typeof PublicauthDeviceRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/(auth)/reset-password': {
      id: '/_public/(auth)/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof PublicauthResetPasswordRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/_landing/': {
      id: '/_public/_landing/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof PublicLandingIndexRouteImport
      parentRoute: typeof PublicLandingRoute
    }
    '/_public/_landing/architecture': {
      id: '/_public/_landing/architecture'
      path: '/architecture'
      fullPath: '/architecture'
      preLoaderRoute: typeof PublicLandingArchitectureRouteImport
      parentRoute: typeof PublicLandingRoute
    }
    '/_public/(auth)/device/': {
      id: '/_public/(auth)/device/'
      path: '/'
      fullPath: '/device/'
      preLoaderRoute: typeof PublicauthDeviceIndexRouteImport
      parentRoute: typeof PublicauthDeviceRoute
    }
    '/_public/(auth)/device/approve': {
      id: '/_public/(auth)/device/approve'
      path: '/approve'
      fullPath: '/device/approve'
      preLoaderRoute: typeof PublicauthDeviceApproveRouteImport
      parentRoute: typeof PublicauthDeviceRoute
    }
    '/_public/_landing/(auth)/signin': {
      id: '/_public/_landing/(auth)/signin'
      path: '/signin'
      fullPath: '/signin'
      preLoaderRoute: typeof PublicLandingauthSigninRouteImport
      parentRoute: typeof PublicLandingRoute
    }
    '/_public/_landing/(auth)/signup': {
      id: '/_public/_landing/(auth)/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof PublicLandingauthSignupRouteImport
      parentRoute: typeof PublicLandingRoute
    }
  }
}

interface AdminRouteChildren {
  AdminDashboardRoute: typeof AdminDashboardRoute
  AdminProfileRoute: typeof AdminProfileRoute
  AdminUsersUserIdRoute: typeof AdminUsersUserIdRoute
  AdminMcpServersIndexRoute: typeof AdminMcpServersIndexRoute
  AdminModelsIndexRoute: typeof AdminModelsIndexRoute
  AdminNodesIndexRoute: typeof AdminNodesIndexRoute
  AdminUsersIndexRoute: typeof AdminUsersIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminDashboardRoute: AdminDashboardRoute,
  AdminProfileRoute: AdminProfileRoute,
  AdminUsersUserIdRoute: AdminUsersUserIdRoute,
  AdminMcpServersIndexRoute: AdminMcpServersIndexRoute,
  AdminModelsIndexRoute: AdminModelsIndexRoute,
  AdminNodesIndexRoute: AdminNodesIndexRoute,
  AdminUsersIndexRoute: AdminUsersIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface PublicLandingRouteChildren {
  PublicLandingArchitectureRoute: typeof PublicLandingArchitectureRoute
  PublicLandingIndexRoute: typeof PublicLandingIndexRoute
  PublicLandingauthSigninRoute: typeof PublicLandingauthSigninRoute
  PublicLandingauthSignupRoute: typeof PublicLandingauthSignupRoute
}

const PublicLandingRouteChildren: PublicLandingRouteChildren = {
  PublicLandingArchitectureRoute: PublicLandingArchitectureRoute,
  PublicLandingIndexRoute: PublicLandingIndexRoute,
  PublicLandingauthSigninRoute: PublicLandingauthSigninRoute,
  PublicLandingauthSignupRoute: PublicLandingauthSignupRoute,
}

const PublicLandingRouteWithChildren = PublicLandingRoute._addFileChildren(
  PublicLandingRouteChildren,
)

interface PublicauthDeviceRouteChildren {
  PublicauthDeviceApproveRoute: typeof PublicauthDeviceApproveRoute
  PublicauthDeviceIndexRoute: typeof PublicauthDeviceIndexRoute
}

const PublicauthDeviceRouteChildren: PublicauthDeviceRouteChildren = {
  PublicauthDeviceApproveRoute: PublicauthDeviceApproveRoute,
  PublicauthDeviceIndexRoute: PublicauthDeviceIndexRoute,
}

const PublicauthDeviceRouteWithChildren =
  PublicauthDeviceRoute._addFileChildren(PublicauthDeviceRouteChildren)

interface PublicRouteChildren {
  PublicLandingRoute: typeof PublicLandingRouteWithChildren
  PublicauthDeviceRoute: typeof PublicauthDeviceRouteWithChildren
  PublicauthResetPasswordRoute: typeof PublicauthResetPasswordRoute
}

const PublicRouteChildren: PublicRouteChildren = {
  PublicLandingRoute: PublicLandingRouteWithChildren,
  PublicauthDeviceRoute: PublicauthDeviceRouteWithChildren,
  PublicauthResetPasswordRoute: PublicauthResetPasswordRoute,
}

const PublicRouteWithChildren =
  PublicRoute._addFileChildren(PublicRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AdminRoute: AdminRouteWithChildren,
  PublicRoute: PublicRouteWithChildren,
  UDotjsRoute: UDotjsRoute,
  ApiSendRoute: ApiSendRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
