/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AdminRouteImport } from './routes/_admin'
import { Route as PublicRouteImport } from './routes/_public'
import { Route as AdminDashboardRouteImport } from './routes/_admin/dashboard'
import { Route as AdminProfileRouteImport } from './routes/_admin/profile'
import { Route as AdminWidgetRouteImport } from './routes/_admin/widget'
import { Route as PublicIndexRouteImport } from './routes/_public/index'
import { Route as PublicDeviceRouteImport } from './routes/_public/device'
import { Route as PublicResetPasswordRouteImport } from './routes/_public/reset-password'
import { Route as PublicSentryExamplePageRouteImport } from './routes/_public/sentry-example-page'
import { Route as PublicSigninRouteImport } from './routes/_public/signin'
import { Route as PublicSignupRouteImport } from './routes/_public/signup'
import { Route as AdminMcpServersIndexRouteImport } from './routes/_admin/mcp-servers/index'
import { Route as AdminModelsIndexRouteImport } from './routes/_admin/models/index'
import { Route as AdminUsersIndexRouteImport } from './routes/_admin/users/index'
import { Route as AdminUsersUserIdRouteImport } from './routes/_admin/users/$userId'
import { Route as PublicDeviceIndexRouteImport } from './routes/_public/device/index'
import { Route as PublicDeviceApproveRouteImport } from './routes/_public/device/approve'

const AdminRoute = AdminRouteImport.update({
  id: '/_admin',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicRoute = PublicRouteImport.update({
  id: '/_public',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminDashboardRoute = AdminDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProfileRoute = AdminProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AdminRoute,
} as any)
const AdminWidgetRoute = AdminWidgetRouteImport.update({
  id: '/widget',
  path: '/widget',
  getParentRoute: () => AdminRoute,
} as any)
const PublicIndexRoute = PublicIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PublicRoute,
} as any)
const PublicDeviceRoute = PublicDeviceRouteImport.update({
  id: '/device',
  path: '/device',
  getParentRoute: () => PublicRoute,
} as any)
const PublicResetPasswordRoute = PublicResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => PublicRoute,
} as any)
const PublicSentryExamplePageRoute = PublicSentryExamplePageRouteImport.update({
  id: '/sentry-example-page',
  path: '/sentry-example-page',
  getParentRoute: () => PublicRoute,
} as any)
const PublicSigninRoute = PublicSigninRouteImport.update({
  id: '/signin',
  path: '/signin',
  getParentRoute: () => PublicRoute,
} as any)
const PublicSignupRoute = PublicSignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => PublicRoute,
} as any)
const AdminMcpServersIndexRoute = AdminMcpServersIndexRouteImport.update({
  id: '/mcp-servers/',
  path: '/mcp-servers/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminModelsIndexRoute = AdminModelsIndexRouteImport.update({
  id: '/models/',
  path: '/models/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminUsersIndexRoute = AdminUsersIndexRouteImport.update({
  id: '/users/',
  path: '/users/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminUsersUserIdRoute = AdminUsersUserIdRouteImport.update({
  id: '/users/$userId',
  path: '/users/$userId',
  getParentRoute: () => AdminRoute,
} as any)
const PublicDeviceIndexRoute = PublicDeviceIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PublicDeviceRoute,
} as any)
const PublicDeviceApproveRoute = PublicDeviceApproveRouteImport.update({
  id: '/approve',
  path: '/approve',
  getParentRoute: () => PublicDeviceRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof PublicIndexRoute
  '/dashboard': typeof AdminDashboardRoute
  '/profile': typeof AdminProfileRoute
  '/widget': typeof AdminWidgetRoute
  '/device': typeof PublicDeviceRouteWithChildren
  '/reset-password': typeof PublicResetPasswordRoute
  '/sentry-example-page': typeof PublicSentryExamplePageRoute
  '/signin': typeof PublicSigninRoute
  '/signup': typeof PublicSignupRoute
  '/users/$userId': typeof AdminUsersUserIdRoute
  '/device/approve': typeof PublicDeviceApproveRoute
  '/mcp-servers/': typeof AdminMcpServersIndexRoute
  '/models/': typeof AdminModelsIndexRoute
  '/users/': typeof AdminUsersIndexRoute
  '/device/': typeof PublicDeviceIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof PublicIndexRoute
  '/dashboard': typeof AdminDashboardRoute
  '/profile': typeof AdminProfileRoute
  '/widget': typeof AdminWidgetRoute
  '/reset-password': typeof PublicResetPasswordRoute
  '/sentry-example-page': typeof PublicSentryExamplePageRoute
  '/signin': typeof PublicSigninRoute
  '/signup': typeof PublicSignupRoute
  '/users/$userId': typeof AdminUsersUserIdRoute
  '/device/approve': typeof PublicDeviceApproveRoute
  '/mcp-servers': typeof AdminMcpServersIndexRoute
  '/models': typeof AdminModelsIndexRoute
  '/users': typeof AdminUsersIndexRoute
  '/device': typeof PublicDeviceIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_admin': typeof AdminRouteWithChildren
  '/_public': typeof PublicRouteWithChildren
  '/_admin/dashboard': typeof AdminDashboardRoute
  '/_admin/profile': typeof AdminProfileRoute
  '/_admin/widget': typeof AdminWidgetRoute
  '/_public/device': typeof PublicDeviceRouteWithChildren
  '/_public/reset-password': typeof PublicResetPasswordRoute
  '/_public/sentry-example-page': typeof PublicSentryExamplePageRoute
  '/_public/signin': typeof PublicSigninRoute
  '/_public/signup': typeof PublicSignupRoute
  '/_public/': typeof PublicIndexRoute
  '/_admin/users/$userId': typeof AdminUsersUserIdRoute
  '/_public/device/approve': typeof PublicDeviceApproveRoute
  '/_admin/mcp-servers/': typeof AdminMcpServersIndexRoute
  '/_admin/models/': typeof AdminModelsIndexRoute
  '/_admin/users/': typeof AdminUsersIndexRoute
  '/_public/device/': typeof PublicDeviceIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/profile'
    | '/widget'
    | '/device'
    | '/reset-password'
    | '/sentry-example-page'
    | '/signin'
    | '/signup'
    | '/users/$userId'
    | '/device/approve'
    | '/mcp-servers/'
    | '/models/'
    | '/users/'
    | '/device/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/profile'
    | '/widget'
    | '/reset-password'
    | '/sentry-example-page'
    | '/signin'
    | '/signup'
    | '/users/$userId'
    | '/device/approve'
    | '/mcp-servers'
    | '/models'
    | '/users'
    | '/device'
  id:
    | '__root__'
    | '/_admin'
    | '/_public'
    | '/_admin/dashboard'
    | '/_admin/profile'
    | '/_admin/widget'
    | '/_public/device'
    | '/_public/reset-password'
    | '/_public/sentry-example-page'
    | '/_public/signin'
    | '/_public/signup'
    | '/_public/'
    | '/_admin/users/$userId'
    | '/_public/device/approve'
    | '/_admin/mcp-servers/'
    | '/_admin/models/'
    | '/_admin/users/'
    | '/_public/device/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AdminRoute: typeof AdminRouteWithChildren
  PublicRoute: typeof PublicRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_admin': {
      id: '/_admin'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public': {
      id: '/_public'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof PublicRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_admin/dashboard': {
      id: '/_admin/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AdminDashboardRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/profile': {
      id: '/_admin/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AdminProfileRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/widget': {
      id: '/_admin/widget'
      path: '/widget'
      fullPath: '/widget'
      preLoaderRoute: typeof AdminWidgetRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_public/': {
      id: '/_public/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof PublicIndexRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/device': {
      id: '/_public/device'
      path: '/device'
      fullPath: '/device'
      preLoaderRoute: typeof PublicDeviceRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/reset-password': {
      id: '/_public/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof PublicResetPasswordRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/sentry-example-page': {
      id: '/_public/sentry-example-page'
      path: '/sentry-example-page'
      fullPath: '/sentry-example-page'
      preLoaderRoute: typeof PublicSentryExamplePageRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/signin': {
      id: '/_public/signin'
      path: '/signin'
      fullPath: '/signin'
      preLoaderRoute: typeof PublicSigninRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/signup': {
      id: '/_public/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof PublicSignupRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_admin/mcp-servers/': {
      id: '/_admin/mcp-servers/'
      path: '/mcp-servers'
      fullPath: '/mcp-servers/'
      preLoaderRoute: typeof AdminMcpServersIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/models/': {
      id: '/_admin/models/'
      path: '/models'
      fullPath: '/models/'
      preLoaderRoute: typeof AdminModelsIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/users/': {
      id: '/_admin/users/'
      path: '/users'
      fullPath: '/users/'
      preLoaderRoute: typeof AdminUsersIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/users/$userId': {
      id: '/_admin/users/$userId'
      path: '/users/$userId'
      fullPath: '/users/$userId'
      preLoaderRoute: typeof AdminUsersUserIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_public/device/': {
      id: '/_public/device/'
      path: '/'
      fullPath: '/device/'
      preLoaderRoute: typeof PublicDeviceIndexRouteImport
      parentRoute: typeof PublicDeviceRoute
    }
    '/_public/device/approve': {
      id: '/_public/device/approve'
      path: '/approve'
      fullPath: '/device/approve'
      preLoaderRoute: typeof PublicDeviceApproveRouteImport
      parentRoute: typeof PublicDeviceRoute
    }
  }
}

interface AdminRouteChildren {
  AdminDashboardRoute: typeof AdminDashboardRoute
  AdminProfileRoute: typeof AdminProfileRoute
  AdminWidgetRoute: typeof AdminWidgetRoute
  AdminUsersUserIdRoute: typeof AdminUsersUserIdRoute
  AdminMcpServersIndexRoute: typeof AdminMcpServersIndexRoute
  AdminModelsIndexRoute: typeof AdminModelsIndexRoute
  AdminUsersIndexRoute: typeof AdminUsersIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminDashboardRoute: AdminDashboardRoute,
  AdminProfileRoute: AdminProfileRoute,
  AdminWidgetRoute: AdminWidgetRoute,
  AdminUsersUserIdRoute: AdminUsersUserIdRoute,
  AdminMcpServersIndexRoute: AdminMcpServersIndexRoute,
  AdminModelsIndexRoute: AdminModelsIndexRoute,
  AdminUsersIndexRoute: AdminUsersIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface PublicDeviceRouteChildren {
  PublicDeviceApproveRoute: typeof PublicDeviceApproveRoute
  PublicDeviceIndexRoute: typeof PublicDeviceIndexRoute
}

const PublicDeviceRouteChildren: PublicDeviceRouteChildren = {
  PublicDeviceApproveRoute: PublicDeviceApproveRoute,
  PublicDeviceIndexRoute: PublicDeviceIndexRoute,
}

const PublicDeviceRouteWithChildren = PublicDeviceRoute._addFileChildren(
  PublicDeviceRouteChildren,
)

interface PublicRouteChildren {
  PublicDeviceRoute: typeof PublicDeviceRouteWithChildren
  PublicResetPasswordRoute: typeof PublicResetPasswordRoute
  PublicSentryExamplePageRoute: typeof PublicSentryExamplePageRoute
  PublicSigninRoute: typeof PublicSigninRoute
  PublicSignupRoute: typeof PublicSignupRoute
  PublicIndexRoute: typeof PublicIndexRoute
}

const PublicRouteChildren: PublicRouteChildren = {
  PublicDeviceRoute: PublicDeviceRouteWithChildren,
  PublicResetPasswordRoute: PublicResetPasswordRoute,
  PublicSentryExamplePageRoute: PublicSentryExamplePageRoute,
  PublicSigninRoute: PublicSigninRoute,
  PublicSignupRoute: PublicSignupRoute,
  PublicIndexRoute: PublicIndexRoute,
}

const PublicRouteWithChildren =
  PublicRoute._addFileChildren(PublicRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AdminRoute: AdminRouteWithChildren,
  PublicRoute: PublicRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
