import type { McpServer, Model, Persona, Provider } from "@kaja/schema/api"
import { TOML } from "bun"

const SECRET_KEY_PATTERN = /key|token|secret|authorization|password/i

function stripSecretEntries(entries: Record<string, string>): Record<string, string> {
  return Object.fromEntries(Object.entries(entries).filter(([key]) => !SECRET_KEY_PATTERN.test(key)))
}

// Excluded from ETag hashing (the route layer hashes the un-prefixed body): a live timestamp would
// otherwise make the ETag change on every request, defeating If-None-Match/304.
function generatedHeader(): string {
  return `# Generated by Kaja API — re-run \`kaja config fetch\` to refresh\n\n`
}

/** models.toml — provider.api_key is never emitted; secrets live in the CLI's secrets.toml. */
export function renderModelsToml(providers: Provider[], models: Model[]): string {
  const providersData = Object.fromEntries(providers.map(p => [p.name, { base_url: p.baseUrl }]))

  // One entry per task: first enabled+free model for that task wins (sort_order/created_at order already applied by the caller).
  const modelsData: Record<string, { model: string; task: string; provider: string }> = {}
  for (const model of models) {
    if (!model.enabled) continue
    const providerName = providers.find(p => p.id === model.providerId)?.name
    if (!providerName) continue
    for (const task of model.tasks) {
      if (modelsData[task]) continue
      modelsData[task] = { model: model.model, task, provider: providerName }
    }
  }

  return generatedHeader() + TOML.stringify({ providers: providersData, models: modelsData })
}

/** mcp.toml — env/headers entries matching a secret-shaped key are dropped; those live in the CLI's secrets.toml [mcp.<id>]. */
export function renderMcpToml(servers: McpServer[]): string {
  const serversData = servers
    .filter(s => s.enabled)
    .map(s =>
      s.url
        ? { id: s.serverId, url: s.url, headers: stripSecretEntries(s.headers) }
        : { id: s.serverId, command: s.command, args: s.args, env: stripSecretEntries(s.env) }
    )

  return generatedHeader() + TOML.stringify({ servers: serversData })
}

/** One persona/<id>.toml file. */
export function renderPersonaToml(persona: Persona): string {
  const data: Record<string, unknown> = {
    label: persona.label,
    ...(persona.when ? { when: persona.when } : {}),
    ...(persona.instructions ? { instructions: persona.instructions } : {}),
    ...(persona.dataset ? { dataset: persona.dataset } : {}),
    ...(Object.keys(persona.models).length > 0 ? { models: persona.models } : {}),
    ...persona.sampling
  }

  return generatedHeader() + TOML.stringify(data)
}
