import type { Model, Provider } from "@kaja/schema/api"
import { TOML } from "bun"

// Excluded from ETag hashing (the route layer hashes the un-prefixed body): a live timestamp would
// otherwise make the ETag change on every request, defeating If-None-Match/304.
function generatedHeader(): string {
  return `# Generated by Kaja API — re-run \`kaja config fetch\` to refresh\n\n`
}

/** models.toml — provider.api_key is never emitted; secrets live in the CLI's secrets.toml. */
export function renderModelsToml(providers: Provider[], models: Model[]): string {
  // One entry per task: first enabled+free model for that task wins (created_at order already applied by the caller).
  // The `free` filter matters — this endpoint is public, so a paid model here would hand anonymous
  // CLI users a model id their own credentials can't reach.
  const modelsData: Record<string, { model: string; task: string; provider: string; context_window?: number }> = {}
  for (const model of models) {
    if (!model.enabled || !model.free) continue
    const providerName = providers.find(p => p.id === model.providerId)?.name
    if (!providerName) continue
    for (const task of model.tasks) {
      if (modelsData[task]) continue
      modelsData[task] = {
        model: model.model,
        task,
        provider: providerName,
        ...(model.contextWindow ? { context_window: model.contextWindow } : {})
      }
    }
  }

  // Only providers an exported model actually references — a provider whose models are all paid or
  // disabled would otherwise appear with nothing pointing at it.
  const usedProviderNames = new Set(Object.values(modelsData).map(entry => entry.provider))
  const providersData = Object.fromEntries(
    providers.filter(p => usedProviderNames.has(p.name)).map(p => [p.name, { base_url: p.baseUrl }])
  )

  return generatedHeader() + TOML.stringify({ providers: providersData, models: modelsData })
}
