// Generated by `bun run scripts/env-types.ts` from packages/schema/env — do not edit by hand.

declare module "bun" {
  interface Env {
    /** Node environment; "development" enables API docs and Better Auth's OpenAPI plugin */
    NODE_ENV?: string
    /** App name attached to every log line */
    KAJA_APP_NAME?: string
    /** Master on/off switch for logging - unset means no log output at all */
    KAJA_LOG_LEVEL?: string
    /** Append JSON logs here instead of pretty-printing/Axiom, in any NODE_ENV */
    KAJA_LOG_FILE?: string
    /** Axiom dataset to ship logs to (node, NODE_ENV=production, no KAJA_LOG_FILE) */
    AXIOM_DATASET?: string
    /** Axiom ingest token (node, NODE_ENV=production, no KAJA_LOG_FILE) */
    AXIOM_TOKEN?: string
    /** Port the API server listens on */
    PORT?: string
    /** Origin allowed for browser requests (also Better Auth's trusted origin and email callback base) */
    CORS_ORIGIN?: string
    /** PostgreSQL connection string */
    DATABASE_URL?: string
    /** Better Auth signing secret */
    BETTER_AUTH_SECRET?: string
    /** Public base URL of this API, used by Better Auth */
    BETTER_AUTH_URL?: string
    /** Public web app URL; falls back to CORS_ORIGIN for the device authorization verification link */
    WEB_PUBLIC_URL?: string
    /** Set when API and web share a parent domain (e.g. ondis.co) to enable cross-subdomain cookies */
    CROSS_PARENT_DOMAIN?: string
    /** SMTP server hostname */
    SMTP_HOST?: string
    /** SMTP server port */
    SMTP_PORT?: string
    /** Use TLS for the SMTP connection */
    SMTP_SECURE?: string
    /** SMTP auth username */
    SMTP_USER?: string
    /** SMTP auth password */
    SMTP_PASS?: string
    /** Set by the CI runner; skips SMTP verification on boot when present */
    CI?: string
    /** Shared-secret bearer token for /config/* — fail-closed: missing/empty denies all config routes */
    CONFIG_API_TOKEN?: string
    /** Set by the Bun test runner; disables rate limiting when present */
    BUN_TEST?: string
    /** Set false to disable global + auth + nasi/widget turn rate limiters */
    RATE_LIMIT_ENABLED?: string
    /** Global rate limit window (ms) */
    RATE_LIMIT_WINDOW_MS?: string
    /** Max requests per window per IP */
    RATE_LIMIT_MAX?: string
    /** Auth rate limit window (ms) */
    AUTH_RATE_LIMIT_WINDOW_MS?: string
    /** Max auth requests per window per IP */
    AUTH_RATE_LIMIT_MAX?: string
    /** /nasi/turn(/stream) rate limit window (ms) */
    NASI_TURN_RATE_LIMIT_WINDOW_MS?: string
    /** Max turns per window per user */
    NASI_TURN_RATE_LIMIT_MAX?: string
    /** /widget/turn rate limit window (ms) */
    WIDGET_TURN_RATE_LIMIT_WINDOW_MS?: string
    /** Max turns per window per (widget key, IP) pair */
    WIDGET_TURN_RATE_LIMIT_MAX?: string
    /** /widget/turn spend-ceiling window (ms) */
    WIDGET_KEY_RATE_LIMIT_WINDOW_MS?: string
    /** Max turns per window per widget key, regardless of visitor/IP */
    WIDGET_KEY_RATE_LIMIT_MAX?: string
    /** Per-user Nasi SQLite directory (one <userId>/nasi.sqlite file each) */
    NASI_DATA_DIR?: string
    /** When set, /nasi turns use a stub model instead of resolving a real provider (test/dev only) */
    NASI_STUB_MODEL?: string
    /** Path to the built embeddable widget bundle, served at GET /widget/widget.js */
    WIDGET_BUNDLE_PATH?: string
  }
}

export {}
