// Generated by `bun run scripts/env-types.ts` from packages/schema/env — do not edit by hand.

declare module "bun" {
  interface Env {
    /** Node environment; "development" enables API docs and Better Auth's OpenAPI plugin */
    NODE_ENV?: string
    /** Port the API server listens on */
    PORT?: string
    /** Origin allowed for browser requests (also Better Auth's trusted origin and email callback base) */
    CORS_ORIGIN?: string
    /** PostgreSQL connection string */
    DATABASE_URL?: string
    /** Better Auth signing secret */
    BETTER_AUTH_SECRET?: string
    /** Shared with the web's SSR_SECRET; the web's server-side calls send it with the visitor's IP so rate limits key on the visitor, not the web host */
    SSR_SECRET?: string
    /** Public base URL of this API, used by Better Auth */
    BETTER_AUTH_URL?: string
    /** Public web app URL; falls back to CORS_ORIGIN for the device authorization verification link */
    WEB_PUBLIC_URL?: string
    /** Set when API and web share a parent domain (e.g. ondis.co) to enable cross-subdomain cookies */
    CROSS_PARENT_DOMAIN?: string
    /** Google OAuth client id; Google sign-in is enabled when both id and secret are set */
    GOOGLE_CLIENT_ID?: string
    /** Google OAuth client secret (redirect URI: <BETTER_AUTH_URL>/auth/callback/google) */
    GOOGLE_CLIENT_SECRET?: string
    /** SMTP server hostname */
    SMTP_HOST?: string
    /** SMTP server port */
    SMTP_PORT?: string
    /** Use TLS for the SMTP connection */
    SMTP_SECURE?: string
    /** SMTP auth username */
    SMTP_USER?: string
    /** SMTP auth password */
    SMTP_PASS?: string
    /** Set by the CI runner; skips SMTP verification on boot when present */
    CI?: string
    /** Shared-secret bearer token for /config/* — fail-closed: missing/empty denies all config routes */
    CONFIG_API_TOKEN?: string
    /** Set by the Bun test runner; disables rate limiting when present */
    BUN_TEST?: string
    /** Set false to disable global + auth + nasi/widget turn rate limiters */
    RATE_LIMIT_ENABLED?: string
    /** Global rate limit window (ms) */
    RATE_LIMIT_WINDOW_MS?: string
    /** Max requests per window per IP */
    RATE_LIMIT_MAX?: string
    /** Auth rate limit window (ms) */
    AUTH_RATE_LIMIT_WINDOW_MS?: string
    /** Max auth requests per window per IP */
    AUTH_RATE_LIMIT_MAX?: string
    /** /nasi/turn(/stream) rate limit window (ms) */
    NASI_TURN_RATE_LIMIT_WINDOW_MS?: string
    /** Max turns per window per user */
    NASI_TURN_RATE_LIMIT_MAX?: string
    /** /widget/turn rate limit window (ms) */
    WIDGET_TURN_RATE_LIMIT_WINDOW_MS?: string
    /** Max turns per window per (widget key, IP) pair */
    WIDGET_TURN_RATE_LIMIT_MAX?: string
    /** /widget/turn spend-ceiling window (ms) */
    WIDGET_KEY_RATE_LIMIT_WINDOW_MS?: string
    /** Max turns per window per widget key, regardless of visitor/IP */
    WIDGET_KEY_RATE_LIMIT_MAX?: string
    /** When set, /nasi turns use a stub model instead of resolving a real provider (test/dev only) */
    NASI_STUB_MODEL?: string
    /** HTTP(S) proxy for cloud fetch_url egress; unset leaves fetch_url out of cloud turns entirely */
    WEB_PROXY?: string
    /** Encrypts users' ability API keys (AES-256-GCM); unset turns key entry off and hides tools that need one */
    USER_SECRET_KEY?: string
    /** Server-wide ability API keys as comma-separated name=key pairs (e.g. brave-search=BSA...); every cloud user shares them, and a user's own key wins */
    ABILITY_KEYS?: string
    /** GitHub owner/repo whose marketplace/ folder the cloud ability catalog is synced from */
    MARKETPLACE_REPO?: string
    /** Branch (or tag) of MARKETPLACE_REPO to sync */
    MARKETPLACE_REF?: string
    /** Base URL of the MCP sandbox (apps/sandbox); with SANDBOX_SECRET it lets cloud turns use stdio MCP abilities */
    SANDBOX_URL?: string
    /** Shared with the sandbox's SANDBOX_SECRET; signs the per-user tokens cloud turns connect with, and the admin dashboard's stats token */
    SANDBOX_SECRET?: string
    /** Object storage bucket for session and tool images */
    STORAGE_BUCKET?: string
    /** Hetzner Object Storage location (fsn1, nbg1, hel1) */
    STORAGE_REGION?: string
    /** S3-compatible endpoint (the compose RustFS) instead of Hetzner; for dev, tests and CI */
    STORAGE_ENDPOINT?: string
    /** Where clients reach STORAGE_ENDPOINT, when that differs (compose's API uses storage:9000, the host localhost:9000); signed URLs name this host */
    STORAGE_PUBLIC_ENDPOINT?: string
    /** Object storage access key (RUSTFS_ACCESS_KEY under STORAGE_ENDPOINT) */
    HCLOUD_ACCESS_KEY_ID?: string
    /** Object storage secret key (RUSTFS_SECRET_KEY under STORAGE_ENDPOINT) */
    HCLOUD_SECRET_ACCESS_KEY?: string
    /** BotFather token; when set, starts the always-on cloud Telegram bot */
    TELEGRAM_BOT_TOKEN?: string
  }
}

export {}
