import { join } from "node:path"
import type { z } from "zod"
import { ApiEnvSchema, CliEnvSchema, WebEnvSchema } from "../packages/schema/env"
import { inspectFields } from "./lib/env-schema"

const rootDir = join(import.meta.dir, "..")

const targets = [
  { schema: ApiEnvSchema, outPath: join(rootDir, "apps/api/src/env.d.ts") },
  { schema: WebEnvSchema, outPath: join(rootDir, "apps/web/src/env.d.ts") },
  { schema: CliEnvSchema, outPath: join(rootDir, "apps/cli/env.d.ts") }
]

function renderEnvDts(schema: z.ZodObject<z.ZodRawShape>): string {
  const fields = inspectFields(schema)
  const lines = fields.map(field => {
    const doc = field.description ? `    /** ${field.description} */\n` : ""
    return `${doc}    ${field.key}?: string`
  })

  return `// Generated by \`bun run scripts/env-types.ts\` from packages/schema/env — do not edit by hand.

declare module "bun" {
  interface Env {
${lines.join("\n")}
  }
}

export {}
`
}

for (const target of targets) {
  const generated = renderEnvDts(target.schema)
  await Bun.write(target.outPath, generated)
  console.log(`Wrote ${target.outPath}`)
}
