// Generated by `bun run scripts/env-types.ts` from packages/schema/env — do not edit by hand.

declare module "bun" {
  interface Env {
    /** Overrides [api].baseUrl from services.toml, for pointing the CLI at a local dev API without editing the file */
    KAJA_API_URL?: string
  }
}

export {}
