export const red = Bun.color("#880808", "ansi")
export const pink = Bun.color("pink", "ansi")
export const cyan = Bun.color("cyan", "ansi")
export const purple = Bun.color("purple", "ansi")
export const green = Bun.color("green", "ansi")
export const lime = Bun.color("lime", "ansi")
export const dimgrey = Bun.color("#6969", "ansi")
