title: Kaja.io Docs
description: Kaja is a free account-based web service for AI agents.
repository: SubZtep/kaja
permalink: pretty
heading_anchors: false

aux_links:
  "Source on GitHub":
    - "//github.com/SubZtep/kaja"
aux_links_new_tab: true

plugins:
  - jekyll-remote-theme
  - jekyll-seo-tag
  - jekyll-github-metadata

remote_theme: just-the-docs/just-the-docs

mermaid:
  version: "11.14.0"

color_scheme: dark
favicon_ico: /images/favicon.ico

gh_edit_link: true
gh_edit_link_text: "Edit this page on GitHub"
gh_edit_repository: "https://github.com/SubZtep/kaja"
gh_edit_branch: "main"
gh_edit_source: "docs"
gh_edit_view_mode: "edit"
