title: 📚 Kaja.io Docs
description: Kaja is a free account-based web service for AI agents.
repository: SubZtep/kaja
permalink: pretty
heading_anchors: false
enable_copy_code_button: true

aux_links:
  "Source on GitHub":
    - "//github.com/SubZtep/kaja"
aux_links_new_tab: true

plugins:
  - jekyll-remote-theme
  - jekyll-seo-tag

remote_theme: just-the-docs/just-the-docs

mermaid:
  version: "11.15.0"

target-blank:
  noopener: false

color_scheme: dark
favicon_ico: /images/favicon.ico
