// Generated by `bun run scripts/env-types.ts` from packages/schema/env — do not edit by hand.

declare module "bun" {
  interface Env {
    /** Node environment; "production" turns on Sentry */
    NODE_ENV?: string
    /** Port the sandbox listens on */
    PORT?: string
    /** Shared with the API's SANDBOX_SECRET; verifies the tokens cloud turns connect with */
    SANDBOX_SECRET?: string
    /** Folder whose mcp/*.toml stdio manifests are the only servers the sandbox runs */
    MARKETPLACE_DIR?: string
    /** JSON file replacing a manifest's command/args for this host, e.g. a preinstalled binary and Chrome flags */
    SANDBOX_OVERRIDES?: string
    /** How long an unused server process is kept warm before it's stopped (ms) */
    SANDBOX_IDLE_MS?: string
    /** Most server processes running at once, over all users */
    SANDBOX_MAX_PROCESSES?: string
  }
}

export {}
