name: Release to Docker Hub

on:
  workflow_dispatch:
    inputs:
      release_api:
        description: "Release API"
        type: boolean
        default: true
      release_web:
        description: "Release Web"
        type: boolean
        default: true

jobs:
  api-docker:
    name: API Build and Push
    if: ${{ inputs.release_api }}
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10

      - name: Get API version
        id: version
        run: |
          VERSION=$(jq -r .version ./apps/api/package.json)
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      - name: Release API
        uses: SubZtep/dockerhub-action@835780a315df2df58f93f656aeb397c8f64e7900
        with:
          dockerhub_repository: ${{ vars.DOCKER_IMAGE_API }}
          dockerhub_username: ${{ vars.DOCKERHUB_USERNAME }}
          dockerhub_token: ${{ secrets.DOCKERHUB_TOKEN }}
          dockerfile: ./apps/api/Dockerfile
          version: ${{ steps.version.outputs.version }}

  web-docker:
    name: Web Build and Push
    if: ${{ inputs.release_web }}
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10

      - name: Get Web version
        id: version
        run: |
          VERSION=$(jq -r .version ./apps/web/package.json)
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      - name: Release Web
        uses: SubZtep/dockerhub-action@835780a315df2df58f93f656aeb397c8f64e7900
        with:
          dockerhub_repository: ${{ vars.DOCKER_IMAGE_WEB }}
          dockerhub_username: ${{ vars.DOCKERHUB_USERNAME }}
          dockerhub_token: ${{ secrets.DOCKERHUB_TOKEN }}
          dockerfile: ./apps/web/Dockerfile
          version: ${{ steps.version.outputs.version }}
          build_args: |
            VITE_API_URL=${{ vars.VITE_API_URL }}
            VITE_APP_URL=${{ vars.VITE_APP_URL }}
